# Generated by Django 5.2.7 on 2025-10-18 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Audio file', upload_to='recordings/')),
                ('original_filename', models.CharField(help_text='Original filename from upload', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type (e.g., audio/webm)', max_length=50)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current transcription processing status', max_length=20)),
                ('transcription_text', models.TextField(blank=True, help_text='Transcribed text content', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audio_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='audio_file',
            field=models.ForeignKey(blank=True, help_text='Associated audio recording file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='chat.audiofile'),
        ),
    ]
