# Generated by Django 5.2.7 on 2025-10-19 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_audiofile_chatmessage_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(db_index=True, help_text='Unique identifier for the voice', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name for the voice (e.g., "Default AI Voice", "My Voice")', max_length=200)),
                ('reference_audio', models.FileField(blank=True, help_text='Reference audio file for voice cloning', null=True, upload_to='voice_profiles/')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default system voice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this voice profile (null for system default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TTSAudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Generated TTS audio file', upload_to='tts_responses/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('mime_type', models.CharField(default='audio/wav', help_text='MIME type of generated audio', max_length=50)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate (seconds)', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(help_text='The chat message this audio is for', on_delete=django.db.models.deletion.CASCADE, related_name='tts_audio', to='chat.chatmessage')),
                ('voice_profile', models.ForeignKey(blank=True, help_text='Voice profile used for generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tts_audio_files', to='chat.voiceprofile')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
