# Generated by Django 5.2.7 on 2025-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_voiceprofile_ttsaudiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprofile',
            name='piper_config_file',
            field=models.FileField(blank=True, help_text='Piper model config file (.onnx.json)', null=True, upload_to='piper_voices/'),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='piper_model_file',
            field=models.FileField(blank=True, help_text='Piper ONNX model file (.onnx)', null=True, upload_to='piper_voices/'),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='tts_backend',
            field=models.CharField(choices=[('piper', 'Piper TTS'), ('coqui', 'Coqui TTS')], default='piper', help_text='TTS engine to use for this voice', max_length=20),
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='reference_audio',
            field=models.FileField(blank=True, help_text='Reference audio file for Coqui voice cloning', null=True, upload_to='voice_profiles/'),
        ),
    ]
