# Generated by Django 5.2.7 on 2025-10-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_voiceprofile_piper_config_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='analysis_error',
            field=models.TextField(blank=True, help_text='Error message if analysis failed', null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of speech analysis', max_length=20),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='speech_analysis',
            field=models.JSONField(blank=True, help_text='Speech characteristic analysis results (confidence, stability, warmth)', null=True),
        ),
    ]
