# Generated by Django 5.2.7 on 2025-10-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_audiofile_analysis_error_audiofile_analysis_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceprofile',
            name='piper_config_file',
        ),
        migrations.RemoveField(
            model_name='voiceprofile',
            name='piper_model_file',
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default voice for this user'),
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='name',
            field=models.CharField(help_text='Display name for the voice (e.g., "My Voice", "Professional Voice")', max_length=200),
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='reference_audio',
            field=models.FileField(default='default.wav', help_text='Reference audio file for voice cloning (6-30 seconds recommended)', upload_to='voice_profiles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='tts_backend',
            field=models.CharField(default='coqui', editable=False, help_text='TTS backend (always Coqui for user profiles)', max_length=20),
        ),
    ]
