# Generated by Django 5.2.7 on 2025-10-20 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_voiceprofile_piper_config_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprofile',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key for anonymous users (for session-based voice profiles)', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default voice for this user/session'),
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this voice profile (for authenticated users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
