"""
Django settings for voice_chat project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []


# Application definition

INSTALLED_APPS = [
    'chat',
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'voice_chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'voice_chat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Voice Chat API',
    'DESCRIPTION': 'Voice Chat API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# Whisper Speech-to-Text Settings
# Model options: 'tiny', 'base', 'small', 'medium', 'large'
WHISPER_MODEL_SIZE = os.getenv('WHISPER_MODEL_SIZE', 'base')

# Local LLM Settings (Ollama)
LOCAL_LLM_ENDPOINT = os.getenv('LOCAL_LLM_ENDPOINT', 'http://localhost:11434/api/chat')
LOCAL_LLM_MODEL = os.getenv('LOCAL_LLM_MODEL', 'deepseek-r1:8b')
LOCAL_LLM_TIMEOUT = int(os.getenv('LOCAL_LLM_TIMEOUT', '120'))  # Request timeout in seconds

# TTS Backend Selection
# Options: 'piper' (fast, CPU-friendly) or 'coqui' (voice cloning, GPU-optimized)
TTS_BACKEND = os.getenv('TTS_BACKEND', 'piper')

# Piper TTS Settings (fast, local, CPU-optimized)
# Multi-language Piper models (auto-selected based on detected language)
PIPER_MODELS = {
    'zh': {
        'model_path': os.getenv('PIPER_ZH_MODEL_PATH', str(BASE_DIR / 'media' / 'piper_voices' / 'zh_CN-huayan-medium.onnx')),
        'config_path': os.getenv('PIPER_ZH_CONFIG_PATH', str(BASE_DIR / 'media' / 'piper_voices' / 'zh_CN-huayan-medium.onnx.json')),
    },
    'en': {
        'model_path': os.getenv('PIPER_EN_MODEL_PATH', str(BASE_DIR / 'media' / 'piper_voices' / 'en_US-lessac-medium.onnx')),
        'config_path': os.getenv('PIPER_EN_CONFIG_PATH', str(BASE_DIR / 'media' / 'piper_voices' / 'en_US-lessac-medium.onnx.json')),
    }
}

# TTS (Text-to-Speech) Settings - Coqui TTS with XTTS v2
COQUITTS_MODEL_NAME = os.getenv('COQUITTS_MODEL_NAME', 'tts_models/multilingual/multi-dataset/xtts_v2')
COQUITTS_OUTPUT_FORMAT = os.getenv('COQUITTS_OUTPUT_FORMAT', 'wav')  # Options: 'wav', 'mp3'
COQUITTS_DEFAULT_SPEAKER_WAV = BASE_DIR / 'media' / 'voice_profiles' / 'default_voice.wav'
# Note: Place a default voice reference audio file at the path above, or upload via admin/API
# The file should be 6-30 seconds of clean speech from the desired voice